language: c
sudo: false

cache:
  directories:
    - $HOME/.opam
    - $HOME/ocaml

install: wget https://raw.githubusercontent.com/ocaml/ocaml-travisci-skeleton/master/.travis-docker.sh
script: bash -ex ./.travis-docker.sh

matrix:
  include:
    - os: linux
      env: OCAML_VERSION=4.07 OCAML_RELEASE=1 WITH_OPAM=0
      stage: Build
    - os: osx
      env: OCAML_VERSION=4.07 OCAML_RELEASE=1 WITH_OPAM=0
      stage: Build_macOS
    - os: linux
      env: OCAML_VERSION=4.07 OCAML_RELEASE=1 WITH_OPAM=1
      stage: Test
      addons:
        apt:
          packages:
            - aspcud
      
