language: c
install:
  - wget https://raw.githubusercontent.com/ocaml/ocaml-travisci-skeleton/master/.travis-opam.sh
  - wget https://raw.githubusercontent.com/dinosaure/ocaml-travisci-skeleton/master/.travis-docgen.sh
script: bash -ex .travis-opam.sh
sudo: true
env:
  global:
  - PACKAGE=spaces_common
  - PACKAGE=grapher
  - PACKAGE=request_manager
  matrix:
  - OCAML_VERSION=4.07
