* Ocaml-Grapherd
** An ocaml port of the classic grapherd
This leads to some mismatches. Grapherd uses arrays to manage the
graph itself and to manage edges in the struct that represents vertex
information. That's a pretty imperative design to be starting with. It
does however use higher-order-functions as it's mechanism for graph
algorithms so that's going to work out well. Also classic grapherd had
a very specific binary protocol that makes little sense to replicate
(as there are no protocol clients anymore) so there's some questions
left about how to manage the API. I'm currently torn between Ajax
(http/json) (easy, universal), janestreet ocaml rpc (easy but
seemingly ocaml specific), Grpc (http2/protobuf), or Thrift.
*** grapher lib
just a graph with vertexes as sets of edges. all the id's being
wrapped in label. this is simple and clear but wrapping means
overhead. Both boxing/unboxing and preventing the use of Bigarray as
the underlying graph/edge collection type.
*** grapherd
unstarted really
*** docker
some work on building a docker CI container has been done but in the
fullness of time it needs to be grown to be a full CI/CD system that
can deliver a container. So work is needes
*** CI
I tried with travis-ci and failed. Failed miserably. The project
builds successfully locally and in my CI container running both alpine
and ubuntu. Maybe its just me but "dune build grapherd/grapherdexe
@runtest" should work seamlessly and shouldn't take 15 minutes.
* Building
** our dependency tree is a bit challenging
*** opam pin add ppx_bin_prot --dev-repo 
*** opam pin add ppx_deriving_yojson --dev-repo
*** install mysql (I used mysql 5.7 from brew on mac osx)
*** fix the environment
#BEGIN_SRC
export PATH=$PATH:/my/path/to/mysql_config
export LDFLAGS="-L/usr/local/opt/openssl/lib"
export CPPFLAGS="-I/usr/local/opt/openssl/include"
#END_SRC
*** opam install mysql
*** opam source ppx_mysql --dev-repo --pin
*** edit ppx_mysql.opam to remove the version upper bound on ppxlib
*** opam update .
*** opam install core httpaf-async higher ppx_compare bisect_ppx
*** hack away!

